### ISSUE TITLE
Files corrupt

### ISSUE THREAD

**Issue by Vlim01** [knaw-huc/loghi#1]
Some files appear to be corrupt which makes installation impossible.

**Comment by rvankoert** [comment]
Could you mention which files? Or provide an error message?

**Comment by Vlim01** [comment]
It hangs after downloading the Docker packages. After extracting I get a corrupt TAR file message. Will see if I can reproduce it again later.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: rvankoert ***@***.***> Datum: 22-04-23  11:48  (GMT+01:00) Aan: knaw-huc/loghi ***@***.***> Cc: Vlim01 ***@***.***>, Author ***@***.***> Onderwerp: Re: [knaw-huc/loghi] Files corrupt (Issue #1) 
Could you mention which files? Or provide an error message?

**Comment by Vlim01** [comment]
I seem to be bouncing from one error to another. Probably a great product, but completely uninstallable with the current documentation and instruction sets. I give up.

**Comment by rvankoert** [comment]
I am sorry to hear this. It looks like you managed to pull the dockers correctly.

The error message you are getting means that either:
- there is some kind of permissions problem accessing the path or
- a (copy-paste?) error in the path
We will work on improving the documentation.

**Comment by TimKoornstra** [comment]
This issue was closed because of inactivity.
