### ISSUE TITLE
git clone command in QuickStart results in error

### ISSUE THREAD

**Issue by rlzijdeman** [knaw-huc/loghi#10]
Hi, 

Following the quickstart procedure in the readme, results in the following error when cloning the repo as instructed:
```
git clone git@githu.com:knaw-huc/loghi.git
Cloning into 'loghi'...
ssh: connect to host githu.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'''

**Comment by stefanklut** [comment]
This appears to be a typo, you are missing a b in github
`git clone git@github.com:knaw-huc/loghi.git`

**Comment by rlzijdeman** [comment]
@stefanklut thank you for your lightning swift reaction. The command you provide results on my machine in the following output (screenshot):
Cloning in, for me, the usual way via git clone https://yadiya does clone the repo.

<img width="854" alt="Screenshot 2023-08-03 at 17 15 01" src="https://github.com/knaw-huc/loghi/assets/3480446/156d89da-a305-4503-95b8-531950ff19fe">

**Comment by stefanklut** [comment]
I think this means you have not set up an ssh key with github. https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account?platform=mac

However if the other method is successful for you perhaps we should consider showcasing other methods of cloning as well

**Comment by rlzijdeman** [comment]
Dear Stefan, you were right! I had not set up an ssh key. I have now two different ones (for authentication and signing), but having closed and opened up a new terminal window, the result of running the command is the same (no access). However, I now how to get it, and you know that this ought to work, so please feel free to close the issue and thanks for noting I had not setup public keys (which I will need anyways!) Best, Richard
