### ISSUE TITLE
java.lang.NullPointerException in 1.3.5 and 1.3.6

### ISSUE THREAD

**Issue by jeroendebok** [knaw-huc/loghi#17]
I'm trying to get Loghi running but ran into some errors. After some digging i found out i only get the error on 1.3.5 and 1.3.6. 1.3.4 and prior are working like a charm.

Im using Ubuntu Server 22.04 running in a VM with 4 vCPU's and 16GB of RAM. When using 1.3.5 and 1.3.6 i get the following error when launching na-pipeline.sh

```
13:53:40.467 [main] DEBUG nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML - page1-abe31edf-1e37-41fe-bfa0-f2dab1640115 appended to dictionary
13:53:40.468 [main] DEBUG nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML - page1-line_4a099af3-55d8-4eff-9754-f8a05dc07185 appended to dictionary
13:53:40.468 [main] DEBUG nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML - page1-e33f3ef5-26e3-42c2-8e81-fd7e4a6b76ac appended to dictionary
13:53:40.487 [pool-1-thread-1] INFO nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML - page1 processing...
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
	at nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML.createProcessingStep(MinionLoghiHTRMergePageXML.java:148)
	at nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML.runFile(MinionLoghiHTRMergePageXML.java:102)
	at nl.knaw.huc.di.images.minions.MinionLoghiHTRMergePageXML.run(MinionLoghiHTRMergePageXML.java:361)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
recalculating reading order
```

It does create a PagXML with some data but i looks like it's only linedata, if you try to read it with the python library there is an error that it's NULL. So the merge of the XML does not happen. (the transcribed text is visible in the logfile)

in 1.3.4 the merge does happen and a XML file bigger in size is created which does contain the transcribed text.

GPU is set to -1 so only CPU is used.

Models used:
Laypa: Baseline
HTR: float32-generic-2023-02-15

**Comment by rvankoert** [comment]
Thank you for bringing this to our attention. It is caused by a missing htr-model config file, which older models don't have. 

We will release 1.3.7 today or tomorrow which will allow older models to be used as well without workarounds.

**Comment by jeroendebok** [comment]
Awesome! Great work on this software!

1 suggestion for the documentation. Please link to the PageXML parser (https://github.com/knaw-huc/pagexml) when talking about the PageXML output the script produces, took me half a day to realise that i had to do more with it.

**Comment by rvankoert** [comment]
1.3.7 has been released. Thanks for the pagexml parser tip. I'll include a link on our github.
