### ISSUE TITLE
spelling of tag <strikethrough>

### ISSUE THREAD

**Issue by icarl-ad** [knaw-huc/loghi#25]
Hi,

I was wondering how the tag <strikethrough> is spelled to mark crossed out baselines in groundtruth data.

Thank you so much for your help!

**Comment by rvankoert** [comment]
Hi,
it is spelled exactly as you mentioned: strikethrough

It should result in the PageXML in a line like this:

**Comment by icarl-ad** [comment]
Thank you!

The tag "strikethrough" is not stored in the expert client by default and I was not able to find out how to correctly add the tag.

Can you tell me how you did it?

**Comment by rvankoert** [comment]
Look at the bottom of the expert client. There should be several buttons for bold/striketrough/super-/subscript.
Follow the red arrow in the image below

![image](https://github.com/knaw-huc/loghi/assets/3168530/4d20b1e6-588f-4885-8119-04ed7d91b67d)

**Comment by icarl-ad** [comment]
Hi,

I had to reopen the issue since I want to clarify something.

Is ground truth marked as strikethrough taken into account during training? Does the transcription indicate where crossed out passages are present after processing?

If not I don´t think it´s valuable to set strikethough tags in ground truth.

Thank you in advance!

**Comment by rvankoert** [comment]
It is taken into account if include_text_styles is enabled in the script loghi/scripts/create-train-data.sh.

This is the default.
