### ISSUE TITLE
Handling of alternative transcription

### ISSUE THREAD

**Issue by icarl-ad** [knaw-huc/loghi#32]
Hi,

I was wondering of Loghi can handle alternative transcription?
We use the transkribus expert client for annotation and if the transcription is uncertain, you can add an alternative transcription.

However, if Loghi can´t handle that it insn´t useful to use this functionaly.

Thanks in advance!

**Comment by rvankoert** [comment]
What do you mean by alternative transcription? Do you mean abbreviation? could you give me an example?

**Comment by rvankoert** [comment]
Hi,

No, unfortunately we are doing nothing with those texts. I think we will also not incorporate them in the near future.
