### ISSUE TITLE
HTR-training without base model does not persist model files

### ISSUE THREAD

**Issue by icarl-ad** [knaw-huc/loghi#33]
Hi there,

how and where can I specify the output directory in which the model files are saved if I train a HTR-model without a base model?

I trained a HTR-model without a base model and I was not able to find the model afterwards. In the script for the training I couldn´t find the variable to specify the output directory.

In the logs it said that the result is saved in the tmp directory but I was not able to open it. Logically after shutting down the server the directory was gone.

Thank you in advance!

**Comment by rvankoert** [comment]
Hi,

Ah, yes that happened to me as well a couple of times. I made some changes in the training script that make it easier to change the output dir. Testing it now and will commit later today.

**Comment by rvankoert** [comment]
Hi,
here is an updated training-script. Look for the "outputdir"  (~line  50) and change it to whatever you want.
https://github.com/knaw-huc/loghi/raw/main/scripts/htr-train-pipeline.sh
