### ISSUE TITLE
HTR-training produces non-running model

### ISSUE THREAD

**Issue by icarl-ad** [knaw-huc/loghi#34]
Hi there,

I started a HTR-training but the resulting model does not run.

The output files also look completely different from the standard model for dutch document:
![image](https://github.com/user-attachments/assets/1b30ceaa-f2dd-4e4b-a23d-9eda9b0c6a60)

On the left you can see the files of the standard model and on the right you can see the output of my training.

Do you have an idea what happened and how I can fix it?

Thank you in advance!

**Comment by rvankoert** [comment]
use best_val as a model. The training output directory contains some metadata and plots about the training run. The actual model is stored in best_val.

**Comment by icarl-ad** [comment]
Thanks, that helped. Although now there was a new error message raised:
`ValueError:` Charlist length (454) does not match model output length (455). If the charlist is correct, try setting use_mask to True.``

I checked the config.json in the best val directory and use_mask is already true.

**Comment by rvankoert** [comment]
check with [icarl-ad](https://github.com/icarl-ad) 
Issue is that older models have an extra character in the charlist. When continuing training using an older foundation model this issue can happen. Workaround is to copy charlist.txt from the old foundation model to the new model. We will solve this in a more permanent manner in one of the upcoming releases.
