### ISSUE TITLE
text region ref sometimes has different structure

### ISSUE THREAD

**Issue by icarl-ad** [knaw-huc/loghi#35]
Hi,

I noticed that the text region reference is sometimes different in the pageXML and I was wondering why and if that means something.

Here´s an example:
![image](https://github.com/user-attachments/assets/609af436-2893-4f77-9adc-9a7d407bd918)

Sometimes there´s a "region_" in the beginning, sometimes there´s just some randomly generated ID.
By the way, this example was processed by Loghi and not manually annotated.

Thank you in advance!

**Comment by rvankoert** [comment]
Hi, 

The reason for this is technical in nature. The regions are assigned an UUID as an id, however id's in pagexml are not allowed to start with a number. "region_" is added to id's that happen to start with a number in order to conform to the PageXML specification.
