### ISSUE TITLE
Preserve custom attribute for TextLine

### ISSUE THREAD

**Issue by fattynoparents** [knaw-huc/loghi#36]
After segmentation I have PageXML files with a custom attribute set for TextLine, like this:
```
<?xml version='1.0' encoding='utf-8'?>
<PcGts xmlns="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15 http://schema.primaresearch.org/PAGE/gts/pagecontent/2019-07-15/pagecontent.xsd">
    <Metadata>
        ...
    </Metadata>
    <Page ...>
        <TextRegion id="textblock_1">
            <Coords points="0,0 0,3120 2320,3120 2320,0" />            
            <TextLine id="2a35572d-b7a7-44f3-9bf5-1d000141b570" custom="structure {type:Marginal;}">
```
but after running the inference process this custom attribute is gone. 

It seems that when Loghi is running the MinionLoghiHTRMergePageXML minion it doesn't preserve such things. 

Is it possible to somehow preserve the line types in this case? Perhaps using the -config_white_list parameter?
Thanks in advance.

**Comment by rvankoert** [comment]
Sorry for the late response. Could you check if in your pipeline you have _MinionRecalculateReadingOrder_ activated somewhere after the region detection?

If so: disable it; it causes all the regions to be detected based on a set of rules instead of using the detected Regions from Laypa.

**Comment by rvankoert** [comment]
Ah, I missed the TextLine part. No currently it is not possible. But it seems like an easy fix to me. I will look into this tomorrow

**Comment by fattynoparents** [comment]
I will be really greatful if you add such s possibility, thank you!

**Comment by rvankoert** [comment]
I wrote a fix. I'll add this to the 2.1.4 release, which will most likely be released tomorrow

**Comment by fattynoparents** [comment]
Awesome, thanks so much!

**Comment by rvankoert** [comment]
it's released now. Just reopen if you run into an issue with the custom attribute not being preserved
