### ISSUE TITLE
Missing charlist.txt

### ISSUE THREAD

**Issue by coret** [knaw-huc/loghi#4]
The [loghi-htr/republic-2023-01-02-base-generic_new14-2022-12-20](https://surfdrive.surf.nl/files/index.php/s/YA8HJuukIUKznSP?path=%2Floghi-htr%2Frepublic-2023-01-02-base-generic_new14-2022-12-20)  folder at https://surfdrive.surf.nl/ is missing the file charlist.txt, na-pipeline.sh needs this file.

Is it save to copy the charlist.txt file from the generic-2023-02-15 folder?

There's also no file.txt in the above mentioned folder, but I don't know if that's a problem.

**Comment by rvankoert** [comment]
It is not save to use a different charlist.txt.
I have added the correct charlist.txt
The file.txt should not be necessary
