### ISSUE TITLE
dockerparams not implemented in na-pipeline-train.sh 

### ISSUE THREAD

**Issue by meniv-nl** [knaw-huc/loghi#5]
running na-pipeline-train.sh didn't work with GPU=-1

my solution: 

1. copied `DOCKERGPUPARAMS` section from na-pipeline.sh 
2. changed `docker run --gpus all --rm  -u` to `docker run $DOCKERGPUPARAMS  -u`

_succes ermee!_

**Comment by TimKoornstra** [comment]
Hi @meniv-nl, thanks for raising this issue. It should be working in the new `scripts/htr-train-pipeline.sh`!
