### ISSUE TITLE
HTR: docker error "failed to create task for container"

### ISSUE THREAD

**Issue by RemcoHulshoff** [knaw-huc/loghi#6]
I'm using wsl2 on W11 with an Ubuntu 20.04 image. I've used all three the 1.2 containers. 

Everything works great (but slowly) with GPU=-1. When GPU=0 then Laypa works fine, the tools work but HTR crashes with this error : 

"
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/1bf59ab7066bcdc8e4cfffbdb3b01c6db9aca097fec2f715f524f289296112a2/merged/usr/lib/x86_64-linux-gnu/libcudadebugger.so.1: file exists: unknown.
"

Full trace included as screenshot:
![image](https://github.com/knaw-huc/loghi/assets/13583400/e0b2df3f-3248-43d3-86e9-6417040f5c57)

the Error looks a lot like this one so I tried their fix but that didn't work here: 
https://forums.developer.nvidia.com/t/wsl-modulus-docker-run-error-libnvidia-ml-so-1-file-exists-unknown/256058

Any ideas?

**Comment by RemcoHulshoff** [comment]
added a Ubuntu 22.04 host to wsl2 and used that, but that did not solve anything. 

sudo apt-get update and sudo apt-get upgrade installed a lot of new versions but that did not solve anything either.

I'm getting the impression that some dependencies need to be installed in de wsl2 linux host that is used to start the docker containers. both the :latest and :1.2 images stop with errors and won't run as-is. Is there a list of dependencies that need to present on the linux host for this to work?

**Comment by rvankoert** [comment]
Hi,

I don't have access to windows, so it's a bit hard for me to reproduce. I built a specific docker that *should* fix the error message, but it is untested. Could you try by replacing in the na-pipeline.sh script:
loghi/docker.htr
with 
loghi/docker.htr-wsl:1.2

**Comment by RemcoHulshoff** [comment]
Thanks for the update! 

this image produces no errors (but a couple of warnings). Time taken and the fact that de CPU is running 100% across all 8 cores / 12 threads (i9 9900K) suggests it is not using the GPU. The system has a RTX 2070 Super so it should be capable of running the job on the GPU right?

**Comment by rvankoert** [comment]
An nvidia 2070 Super should work. The software was developed using one of those. 

Which cuda-version are you running on the host?

**Comment by RemcoHulshoff** [comment]
W11 is using the 535.98 drivers (march or april this year I think). I have installed no additional software inside the linux host thats running inside wsl2.

**Comment by rvankoert** [comment]
what output do you get when you run:

docker run --gpus all -ti loghi/docker.htr-wsl:1.2 bash -c "apt-get install -y nvidia-utils-495; nvidia-smi"

**Comment by RemcoHulshoff** [comment]
![image](https://github.com/knaw-huc/loghi/assets/13583400/06a9acb3-a420-4608-8b77-7305cfa096dd)

**Comment by rvankoert** [comment]
I think I removed a little bit too much from the docker.htr....
If you run:
`docker run --gpus all -ti loghi/docker.htr-wsl:1.2 python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"`

do you get as an result:?
[]

if so: either wait for the new docker.htr-wsl that's now being push or more quickly build your own derived docker using as contents for the Dockerfile:

```
FROM loghi/docker.htr
RUN rm -rf \
    /usr/lib/x86_64-linux-gnu/libcuda.so* \
    /usr/lib/x86_64-linux-gnu/libnvcuvid.so* \
    /usr/lib/x86_64-linux-gnu/libnvidia-*.so* \
    /usr/lib/x86_64-linux-gnu/libcudadebugger.so* \
    /usr/lib/firmware \
    /usr/local/cuda/compat/lib
```
and then run:

`docker build --squash . -t loghi/docker.htr-wsl:1.2`

but you might get new errors like:
`nvidia-container-cli: mount error: file creation failed: /var/lib/docker/overlay2/1bf59ab7066bcdc8e4cfffbdb3b01c6db9aca097fec2f715f524f289296112a2/merged/usr/lib/x86_64-linux-gnu/libcudadebugger.so.1: file exists: unknown.
`

**Comment by RemcoHulshoff** [comment]
I get: 
![image](https://github.com/knaw-huc/loghi/assets/13583400/a1143477-bb06-40b9-abf4-db254de58060)

**Comment by rvankoert** [comment]
I'm sorry use:
loghi/docker.htr:1.2

**Comment by RemcoHulshoff** [comment]
output of image based of :1.2

![image](https://github.com/knaw-huc/loghi/assets/13583400/8ac0c58f-3733-4af8-8d25-f21ccb040bd1)

**Comment by rvankoert** [comment]
Is this the output of na-pipeline.sh using the loghi/docker.htr-wsl:1.2 after you ran the docker build command?

**Comment by RemcoHulshoff** [comment]
that is the output of the na-pipeline.sh.

**Comment by rvankoert** [comment]
Strange. Totally not what i expected. Could you try re-downloading the loghi/docker.htr-wsl:1.2 ? And run na-pipeline.sh again? If that doesn't show some improvement then I'll try getting my hands on a Windows machine tomorrow.

**Comment by RemcoHulshoff** [comment]
sorry to say, same result: 

![image](https://github.com/knaw-huc/loghi/assets/13583400/c1c0ff0b-4c81-4847-8c8f-009014085a4e)

**Comment by rvankoert** [comment]
Could you send me the contents of your na-pipeline.sh ?  I'll look into it tomorrow

**Comment by RemcoHulshoff** [comment]
[na-pipeline.zip](https://github.com/knaw-huc/loghi/files/12209619/na-pipeline.zip)

sure. here u go.

**Comment by rvankoert** [comment]
could you remove line 139 from the na-pipeline script entirely? It starts with:
#        docker run $DOCKERGPUPARAMS --rm -m 32000m --shm-size 10240m -ti -v $tmpdir:$tmpdir docker.htr python3

**Comment by RemcoHulshoff** [comment]
Against my expectations that appears to have done it. I thought that line was commented out. The script ran to completion and it looks like it ran the HTR on the GPU.

well done & thank you! :-)

**Comment by rvankoert** [comment]
Thanks for the feedback :)
We will most likely incorporate these changes in docker.htr in the future. That will probably be version 1.3
